### Pandas - iloc

    Berikut ini cara yang dapat kita gunakan dari fungsi iloc.

In [24]:
#memasukan modul yang digunakan
import pandas as pd
import numpy as np

In [25]:
#memasukan data
df = pd.read_csv("C:/Users/Yanie/PT Premier Optima Sattiga/adult.csv")

In [26]:
#membaca data
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,prediction
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [31]:
#melihat jumlah baris yang kosong dan memasukannya hasilnya ke dalam variabel df1
df1 = df.isnull().sum()

In [32]:
#mengecek apakah ada missing value atau tidak secara keseluruhan
df2 = df1.isnull().any().any()
df2

False

In [37]:
#untuk menampilkan data dengan baris kelipatan 3 dan kolom kelipatan 3
df.iloc[::2,::2]

,age,fnlwgt,education-num,occupation,race,capital-gain,hours-per-week,prediction
0,39,77516,13,Adm-clerical,White,2174,40,<=50K
2,38,215646,9,Handlers-cleaners,White,0,40,<=50K
4,28,338409,13,Prof-specialty,Black,0,40,<=50K
6,49,160187,5,Other-service,Black,0,16,<=50K
8,31,45781,14,Prof-specialty,White,14084,50,>50K
10,37,280464,10,Exec-managerial,Black,0,80,>50K
12,23,122272,13,Adm-clerical,White,0,30,<=50K
14,40,121772,11,Craft-repair,Asian-Pac-Islander,0,40,>50K
16,25,176756,9,Farming-fishing,White,0,35,<=50K
18,38,28887,7,Sales,White,0,50,<=50K
20,40,193524,16,Prof-specialty,White,0,60,>50K
22,35,76845,5,Farming-fishing,Black,0,40,<=50K
24,59,109015,9,Tech-support,White,0,40,<=50K
26,19,168294,9,Craft-repair,White,0,40,<=50K
28,39,367260,9,Exec-managerial,White,0,80,<=50K
30,23,190709,12,Protective-serv,White,0,52,<=50K
32,45,386940,13,Exec-managerial,White,0,40,<=50K
34,22,311512,10,Other-service,Black,0,15,<=50K
36,21,197200,10,Machine-op-inspct,White,0,40,<=50K
38,31,84154,10,Sales,White,0,38,>50K
40,31,507875,5,Machine-op-inspct,White,0,43,<=50K
42,24,172987,13,Tech-support,White,0,50,<=50K
44,25,289980,9,Handlers-cleaners,White,0,35,<=50K
46,53,144361,9,Machine-op-inspct,White,0,38,<=50K
48,41,101603,11,Craft-repair,White,0,40,<=50K
50,25,32275,10,Exec-managerial,Other,0,40,<=50K
52,47,51835,15,Prof-specialty,White,0,60,>50K
54,47,109832,9,Exec-managerial,White,0,60,<=50K
56,46,216666,3,Machine-op-inspct,White,0,40,<=50K
58,41,147372,9,Adm-clerical,White,0,48,<=50K
...,...,...,...,...,...,...,...,...
48782,60,127084,4,Transport-moving,White,0,60,<=50K.
48784,30,201697,9,Other-service,White,0,35,<=50K.
48786,52,240612,9,Prof-specialty,White,0,40,>50K.
48788,28,109001,9,Handlers-cleaners,White,0,40,<=50K.
48790,29,335015,9,Craft-repair,White,0,48,<=50K.
48792,34,408813,9,Craft-repair,White,0,40,>50K.
48794,29,170482,9,Protective-serv,Black,0,40,<=50K.
48796,27,133770,13,Prof-specialty,Asian-Pac-Islander,2202,52,<=50K.
48798,30,34572,15,Prof-specialty,White,0,80,>50K.
48800,73,144872,9,NaN,White,0,25,<=50K.
48802,51,29887,13,Tech-support,White,0,40,<=50K.
48804,42,275677,11,Adm-clerical,White,0,50,<=50K.
48806,51,311631,13,Sales,White,0,40,>50K.
48808,24,374763,7,Craft-repair,White,0,40,<=50K.
48810,31,112115,9,Machine-op-inspct,White,0,40,<=50K.
48812,81,26711,11,NaN,White,2936,20,<=50K.
48814,39,229647,13,Tech-support,White,0,40,<=50K.
48816,43,23157,14,Exec-managerial,White,0,50,>50K.
48818,73,159691,10,Exec-managerial,White,0,40,<=50K.
48820,66,344436,9,Sales,White,0,8,<=50K.
48822,40,202168,15,Prof-specialty,White,15024,55,>50K.
48824,22,269623,10,Craft-repair,White,0,40,<=50K.
48826,50,139347,14,Prof-specialty,White,0,40,>50K.
48828,38,247547,11,Adm-clerical,Black,0,40,<=50K.
48830,32,173449,9,Handlers-cleaners,White,0,40,<=50K.
48832,61,89686,9,Sales,White,0,48,<=50K.
48834,25,350977,9,Other-service,White,0,40,<=50K.
48836,33,245211,13,Prof-specialty,White,0,40,<=50K.
48838,64,321403,9,NaN,Black,0,40,<=50K.
48840,44,83891,13,Adm-clerical,Asian-Pac-Islander,5455,40,<=50K.

In [44]:
#untuk menampilkan data dengan baris genap dan kolom ganjil misalnya age, fnlwgt, education-num, occupation dst.
df.iloc[::2, 0::2]

,age,fnlwgt,education-num,occupation,race,capital-gain,hours-per-week,prediction
0,39,77516,13,Adm-clerical,White,2174,40,<=50K
2,38,215646,9,Handlers-cleaners,White,0,40,<=50K
4,28,338409,13,Prof-specialty,Black,0,40,<=50K
6,49,160187,5,Other-service,Black,0,16,<=50K
8,31,45781,14,Prof-specialty,White,14084,50,>50K
10,37,280464,10,Exec-managerial,Black,0,80,>50K
12,23,122272,13,Adm-clerical,White,0,30,<=50K
14,40,121772,11,Craft-repair,Asian-Pac-Islander,0,40,>50K
16,25,176756,9,Farming-fishing,White,0,35,<=50K
18,38,28887,7,Sales,White,0,50,<=50K
20,40,193524,16,Prof-specialty,White,0,60,>50K
22,35,76845,5,Farming-fishing,Black,0,40,<=50K
24,59,109015,9,Tech-support,White,0,40,<=50K
26,19,168294,9,Craft-repair,White,0,40,<=50K
28,39,367260,9,Exec-managerial,White,0,80,<=50K
30,23,190709,12,Protective-serv,White,0,52,<=50K
32,45,386940,13,Exec-managerial,White,0,40,<=50K
34,22,311512,10,Other-service,Black,0,15,<=50K
36,21,197200,10,Machine-op-inspct,White,0,40,<=50K
38,31,84154,10,Sales,White,0,38,>50K
40,31,507875,5,Machine-op-inspct,White,0,43,<=50K
42,24,172987,13,Tech-support,White,0,50,<=50K
44,25,289980,9,Handlers-cleaners,White,0,35,<=50K
46,53,144361,9,Machine-op-inspct,White,0,38,<=50K
48,41,101603,11,Craft-repair,White,0,40,<=50K
50,25,32275,10,Exec-managerial,Other,0,40,<=50K
52,47,51835,15,Prof-specialty,White,0,60,>50K
54,47,109832,9,Exec-managerial,White,0,60,<=50K
56,46,216666,3,Machine-op-inspct,White,0,40,<=50K
58,41,147372,9,Adm-clerical,White,0,48,<=50K
...,...,...,...,...,...,...,...,...
48782,60,127084,4,Transport-moving,White,0,60,<=50K.
48784,30,201697,9,Other-service,White,0,35,<=50K.
48786,52,240612,9,Prof-specialty,White,0,40,>50K.
48788,28,109001,9,Handlers-cleaners,White,0,40,<=50K.
48790,29,335015,9,Craft-repair,White,0,48,<=50K.
48792,34,408813,9,Craft-repair,White,0,40,>50K.
48794,29,170482,9,Protective-serv,Black,0,40,<=50K.
48796,27,133770,13,Prof-specialty,Asian-Pac-Islander,2202,52,<=50K.
48798,30,34572,15,Prof-specialty,White,0,80,>50K.
48800,73,144872,9,NaN,White,0,25,<=50K.
48802,51,29887,13,Tech-support,White,0,40,<=50K.
48804,42,275677,11,Adm-clerical,White,0,50,<=50K.
48806,51,311631,13,Sales,White,0,40,>50K.
48808,24,374763,7,Craft-repair,White,0,40,<=50K.
48810,31,112115,9,Machine-op-inspct,White,0,40,<=50K.
48812,81,26711,11,NaN,White,2936,20,<=50K.
48814,39,229647,13,Tech-support,White,0,40,<=50K.
48816,43,23157,14,Exec-managerial,White,0,50,>50K.
48818,73,159691,10,Exec-managerial,White,0,40,<=50K.
48820,66,344436,9,Sales,White,0,8,<=50K.
48822,40,202168,15,Prof-specialty,White,15024,55,>50K.
48824,22,269623,10,Craft-repair,White,0,40,<=50K.
48826,50,139347,14,Prof-specialty,White,0,40,>50K.
48828,38,247547,11,Adm-clerical,Black,0,40,<=50K.
48830,32,173449,9,Handlers-cleaners,White,0,40,<=50K.
48832,61,89686,9,Sales,White,0,48,<=50K.
48834,25,350977,9,Other-service,White,0,40,<=50K.
48836,33,245211,13,Prof-specialty,White,0,40,<=50K.
48838,64,321403,9,NaN,Black,0,40,<=50K.
48840,44,83891,13,Adm-clerical,Asian-Pac-Islander,5455,40,<=50K.

In [71]:
#fibonacci_numbers
fibonacci_numbers = [0, 1]
for i in range(50):
    fibonacci_numbers.append(fibonacci_numbers[i]+fibonacci_numbers[i+1])

In [70]:
#untuk menampilkan data dengan baris data adalah indeks dari fibonacci_numbers
df.iloc[fibonacci_numbers]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,prediction
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
34,22,State-gov,311512,Some-college,10,Married-civ-spouse,Other-service,Husband,Black,Male,0,0,15,United-States,<=50K
55,43,Private,237993,Some-college,10,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
89,43,Federal-gov,410867,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,>50K
144,70,Private,105376,Some-college,10,Never-married,Tech-support,Other-relative,White,Male,0,0,40,United-States,<=50K
233,33,Private,110978,Some-college,10,Divorced,Craft-repair,Other-relative,Other,Female,0,0,40,United-States,<=50K
377,23,Private,35633,Some-college,10,Never-married,Sales,Not-in-family,White,Male,0,0,40,United-States,<=50K
610,52,Private,200853,Masters,14,Divorced,Prof-specialty,Not-in-family,White,Female,6849,0,60,United-States,<=50K
987,47,Private,335973,HS-grad,9,Divorced,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
1597,37,Private,910398,Bachelors,13,Never-married,Sales,Not-in-family,Black,Female,0,0,40,United-States,<=50K
2584,57,Private,348430,1st-4th,2,Divorced,Craft-repair,Unmarried,White,Male,0,0,40,Portugal,<=50K
4181,63,Private,154526,Some-college,10,Widowed,Other-service,Not-in-family,White,Female,0,0,40,United-States,<=50K
6765,28,Private,38918,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,Germany,>50K
10946,29,Private,135296,Assoc-voc,11,Never-married,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
17711,21,Private,78170,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0,0,42,United-States,<=50K
28657,46,Private,465974,11th,7,Never-married,Transport-moving,Own-child,White,Male,0,0,30,United-States,<=50K
46368,48,Private,43479,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,5013,0,40,United-States,<=50K.

                            ##Semoga Bermanfaat
                            ##@Raspiani_